build:
  nodes:
    analysis:
      root_path: './backend'
      project_setup:
        before:
          - nvm install 16
          - nvm use 16
        override:
          - npm install
      tests:
        override:
          # Run ESLint analysis
          - command: npm run lint:report-checkstyle
            analysis:
              format: eslint-checkstyle

          # Run tests with coverage
          - command: npm run test:full-cov
            coverage:
              file: coverage/clover.xml
              format: clover

tools:
  eslint:
    enabled: true
    config:
      extensions:
        - .ts

filter:
  excluded_paths:
    - 'tests/*'
    - 'node_modules/*'