name: Backend Tests

on:
  workflow_dispatch: 
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Print JWT_SECRET
        run: echo $JWT_SECRET
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Run e2e tests
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm run test:e2e